# Build and test a CMake project with vcpkg and CMakePresets.json on Windows and Linux
name: CI

# Run CI on every push
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Build with CMake and run CTest, use vcpkg to acquire dependencies and cache in GitHub Packages
  build:

    # Setup cross-platform build on Windows and Linux
    strategy:
      matrix:
        os: ['windows-2019', 'ubuntu-20.04']
        include:
          - os: 'windows-2019'
            triplet: 'x86-windows'
            mono: ''
          - os: 'ubuntu-20.04'
            triplet: 'x64-linux'
            mono: 'mono'

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      # Fetch --unshallow
      - name: 'vcpkg fetch --unshallow'
        run: |
          git -C vcpkg fetch --unshallow
      
      # Install CMake 3.20 
      - uses: lukka/get-cmake@cmake-3.20

      # Setup vcpkg
      - name: Restore from cache and run vcpkg
        uses: lukka/run-vcpkg@v6
        with:
          # Location of the vcpkg as submodule of the repository.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          setupOnly: true 
      
      # Setup NuGet credentials for uploading cached packages (and download if repo is private)
      - name: 'Setup NuGet credentials'
        shell: 'bash'
        run: >
          ${{ matrix.mono }} `vcpkg/vcpkg fetch nuget | tail -n 1` 
          sources add 
          -source "https://nuget.pkg.github.com/WillBuik/index.json"
          -storepasswordincleartext
          -name "WillBuikGithub"
          -username "WillBuik"
          -password "${{ secrets.GITHUB_TOKEN }}"

       # Update apt
      - name: 'Update apt' 
        shell: 'bash'
        run: 'sudo apt-get update'
        if: ${{ matrix.os == 'ubuntu-20.04' }}
          
       # Install apt-dependencies on Linux for glfw3
      - name: 'Apt dependencies'
        shell: 'bash'
        run: 'sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev'
        if: ${{ matrix.os == 'ubuntu-20.04' }}

        # Configure and build on Windows with Ninja and cl
      - uses: ilammy/msvc-dev-cmd@v1  
        with:
          arch: 'x86'
      - name: 'Configure and build on Windows'
        run: |
          cmake --preset=x86-windows 
          cmake --build --preset verbose-build
        env:
            VCPKG_BINARY_SOURCES: 'clear;nuget,WillBuikGithub,readwrite'
        if: ${{ matrix.os == 'windows-2019' }}

        # Configure and build on Linux with Ninja and gcc
      - name: 'Configure and build on Linux'
        run: |
          cmake --preset=linux-base 
          cmake --build --preset linux-clean-build
        env:
            VCPKG_BINARY_SOURCES: 'clear;nuget,WillBuikGithub,readwrite'
        if: ${{ matrix.os == 'ubuntu-20.04' }}

        # Run CTest on Windows
      - name: 'Run CTest on Windows'
        shell: 'bash'
        run: 'ctest --preset windows-core-test'
        if: ${{ matrix.os == 'windows-2019' }}

        # Run CTest on Linux
      - name: 'Run CTest on Linux'
        shell: 'bash'
        run: 'ctest --preset linux-core-test'
        if: ${{ matrix.os == 'ubuntu-20.04' }}
    
